export const COUNTRIES = [
    { code: 'AF', name: 'Afghanistan (阿富汗)' },
    { code: 'AL', name: 'Albania (阿尔巴尼亚)' },
    { code: 'DZ', name: 'Algeria (阿尔及利亚)' },
    { code: 'AS', name: 'American Samoa (美属萨摩亚)' },
    { code: 'AD', name: 'Andorra (安道尔)' },
    { code: 'AO', name: 'Angola (安哥拉)' },
    { code: 'AI', name: 'Anguilla (安圭拉)' },
    { code: 'AQ', name: 'Antarctica (南极洲)' },
    { code: 'AG', name: 'Antigua and Barbuda (安提瓜和巴布达)' },
    { code: 'AR', name: 'Argentina (阿根廷)' },
    { code: 'AM', name: 'Armenia (亚美尼亚)' },
    { code: 'AW', name: 'Aruba (阿鲁巴)' },
    { code: 'AU', name: 'Australia (澳大利亚)' },
    { code: 'AT', name: 'Austria (奥地利)' },
    { code: 'AZ', name: 'Azerbaijan (阿塞拜疆)' },
    { code: 'BS', name: 'Bahamas (巴哈马)' },
    { code: 'BH', name: 'Bahrain (巴林)' },
    { code: 'BD', name: 'Bangladesh (孟加拉国)' },
    { code: 'BB', name: 'Barbados (巴巴多斯)' },
    { code: 'BY', name: 'Belarus (白俄罗斯)' },
    { code: 'BE', name: 'Belgium (比利时)' },
    { code: 'BZ', name: 'Belize (伯利兹)' },
    { code: 'BJ', name: 'Benin (贝宁)' },
    { code: 'BM', name: 'Bermuda (百慕大)' },
    { code: 'BT', name: 'Bhutan (不丹)' },
    { code: 'BO', name: 'Bolivia (玻利维亚)' },
    { code: 'BA', name: 'Bosnia and Herzegovina (波斯尼亚和黑塞哥维那)' },
    { code: 'BW', name: 'Botswana (博茨瓦纳)' },
    { code: 'BV', name: 'Bouvet Island (布韦岛)' },
    { code: 'BR', name: 'Brazil (巴西)' },
    { code: 'IO', name: 'British Indian Ocean Territory (英属印度洋领地)' },
    { code: 'BN', name: 'Brunei Darussalam (文莱)' },
    { code: 'BG', name: 'Bulgaria (保加利亚)' },
    { code: 'BF', name: 'Burkina Faso (布基纳法索)' },
    { code: 'BI', name: 'Burundi (布隆迪)' },
    { code: 'KH', name: 'Cambodia (柬埔寨)' },
    { code: 'CM', name: 'Cameroon (喀麦隆)' },
    { code: 'CA', name: 'Canada (加拿大)' },
    { code: 'CV', name: 'Cape Verde (佛得角)' },
    { code: 'KY', name: 'Cayman Islands (开曼群岛)' },
    { code: 'CF', name: 'Central African Republic (中非共和国)' },
    { code: 'TD', name: 'Chad (乍得)' },
    { code: 'CL', name: 'Chile (智利)' },
    { code: 'CN', name: 'China (中国)' },
    { code: 'CX', name: 'Christmas Island (圣诞岛)' },
    { code: 'CC', name: 'Cocos (Keeling) Islands (科科斯群岛)' },
    { code: 'CO', name: 'Colombia (哥伦比亚)' },
    { code: 'KM', name: 'Comoros (科摩罗)' },
    { code: 'CG', name: 'Congo (刚果)' },
    { code: 'CD', name: 'Congo, Democratic Republic (刚果民主共和国)' },
    { code: 'CK', name: 'Cook Islands (库克群岛)' },
    { code: 'CR', name: 'Costa Rica (哥斯达黎加)' },
    { code: 'CI', name: 'Cote D\'Ivoire (科特迪瓦)' },
    { code: 'HR', name: 'Croatia (克罗地亚)' },
    { code: 'CU', name: 'Cuba (古巴)' },
    { code: 'CY', name: 'Cyprus (塞浦路斯)' },
    { code: 'CZ', name: 'Czech Republic (捷克)' },
    { code: 'DK', name: 'Denmark (丹麦)' },
    { code: 'DJ', name: 'Djibouti (吉布提)' },
    { code: 'DM', name: 'Dominica (多米尼克)' },
    { code: 'DO', name: 'Dominican Republic (多米尼加共和国)' },
    { code: 'EC', name: 'Ecuador (厄瓜多尔)' },
    { code: 'EG', name: 'Egypt (埃及)' },
    { code: 'SV', name: 'El Salvador (萨尔瓦多)' },
    { code: 'GQ', name: 'Equatorial Guinea (赤道几内亚)' },
    { code: 'ER', name: 'Eritrea (厄立特里亚)' },
    { code: 'EE', name: 'Estonia (爱沙尼亚)' },
    { code: 'ET', name: 'Ethiopia (埃塞俄比亚)' },
    { code: 'FK', name: 'Falkland Islands (马尔维纳斯群岛)' },
    { code: 'FO', name: 'Faroe Islands (法罗群岛)' },
    { code: 'FJ', name: 'Fiji (斐济)' },
    { code: 'FI', name: 'Finland (芬兰)' },
    { code: 'FR', name: 'France (法国)' },
    { code: 'GF', name: 'French Guiana (法属圭亚那)' },
    { code: 'PF', name: 'French Polynesia (法属波利尼西亚)' },
    { code: 'TF', name: 'French Southern Territories (法属南部领地)' },
    { code: 'GA', name: 'Gabon (加蓬)' },
    { code: 'GM', name: 'Gambia (冈比亚)' },
    { code: 'GE', name: 'Georgia (格鲁吉亚)' },
    { code: 'DE', name: 'Germany (德国)' },
    { code: 'GH', name: 'Ghana (加纳)' },
    { code: 'GI', name: 'Gibraltar (直布罗陀)' },
    { code: 'GR', name: 'Greece (希腊)' },
    { code: 'GL', name: 'Greenland (格陵兰)' },
    { code: 'GD', name: 'Grenada (格林纳达)' },
    { code: 'GP', name: 'Guadeloupe (瓜德罗普)' },
    { code: 'GU', name: 'Guam (关岛)' },
    { code: 'GT', name: 'Guatemala (危地马拉)' },
    { code: 'GN', name: 'Guinea (几内亚)' },
    { code: 'GW', name: 'Guinea-Bissau (几内亚比绍)' },
    { code: 'GY', name: 'Guyana (圭亚那)' },
    { code: 'HT', name: 'Haiti (海地)' },
    { code: 'HM', name: 'Heard Island and Mcdonald Islands (赫德岛和麦克唐纳群岛)' },
    { code: 'VA', name: 'Holy See (Vatican City State) (梵蒂冈)' },
    { code: 'HN', name: 'Honduras (洪都拉斯)' },
    { code: 'HK', name: 'Hong Kong (香港)' },
    { code: 'HU', name: 'Hungary (匈牙利)' },
    { code: 'IS', name: 'Iceland (冰岛)' },
    { code: 'IN', name: 'India (印度)' },
    { code: 'ID', name: 'Indonesia (印度尼西亚)' },
    { code: 'IR', name: 'Iran (伊朗)' },
    { code: 'IQ', name: 'Iraq (伊拉克)' },
    { code: 'IE', name: 'Ireland (爱尔兰)' },
    { code: 'IL', name: 'Israel (以色列)' },
    { code: 'IT', name: 'Italy (意大利)' },
    { code: 'JM', name: 'Jamaica (牙买加)' },
    { code: 'JP', name: 'Japan (日本)' },
    { code: 'JO', name: 'Jordan (约旦)' },
    { code: 'KZ', name: 'Kazakhstan (哈萨克斯坦)' },
    { code: 'KE', name: 'Kenya (肯尼亚)' },
    { code: 'KI', name: 'Kiribati (基里巴斯)' },
    { code: 'KP', name: 'Korea, Democratic People\'s Republic of (朝鲜)' },
    { code: 'KR', name: 'Korea, Republic of (韩国)' },
    { code: 'KW', name: 'Kuwait (科威特)' },
    { code: 'KG', name: 'Kyrgyzstan (吉尔吉斯斯坦)' },
    { code: 'LA', name: 'Lao People\'s Democratic Republic (老挝)' },
    { code: 'LV', name: 'Latvia (拉脱维亚)' },
    { code: 'LB', name: 'Lebanon (黎巴嫩)' },
    { code: 'LS', name: 'Lesotho (莱索托)' },
    { code: 'LR', name: 'Liberia (利比里亚)' },
    { code: 'LY', name: 'Libyan Arab Jamahiriya (利比亚)' },
    { code: 'LI', name: 'Liechtenstein (列支敦士登)' },
    { code: 'LT', name: 'Lithuania (立陶宛)' },
    { code: 'LU', name: 'Luxembourg (卢森堡)' },
    { code: 'MO', name: 'Macao (澳门)' },
    { code: 'MK', name: 'Macedonia (马其顿)' },
    { code: 'MG', name: 'Madagascar (马达加斯加)' },
    { code: 'MW', name: 'Malawi (马拉维)' },
    { code: 'MY', name: 'Malaysia (马来西亚)' },
    { code: 'MV', name: 'Maldives (马尔代夫)' },
    { code: 'ML', name: 'Mali (马里)' },
    { code: 'MT', name: 'Malta (马耳他)' },
    { code: 'MH', name: 'Marshall Islands (马绍尔群岛)' },
    { code: 'MQ', name: 'Martinique (马提尼克)' },
    { code: 'MR', name: 'Mauritania (毛里塔尼亚)' },
    { code: 'MU', name: 'Mauritius (毛里求斯)' },
    { code: 'YT', name: 'Mayotte (马约特)' },
    { code: 'MX', name: 'Mexico (墨西哥)' },
    { code: 'FM', name: 'Micronesia (密克罗尼西亚)' },
    { code: 'MD', name: 'Moldova (摩尔多瓦)' },
    { code: 'MC', name: 'Monaco (摩纳哥)' },
    { code: 'MN', name: 'Mongolia (蒙古)' },
    { code: 'MS', name: 'Montserrat (蒙特塞拉特)' },
    { code: 'MA', name: 'Morocco (摩洛哥)' },
    { code: 'MZ', name: 'Mozambique (莫桑比克)' },
    { code: 'MM', name: 'Myanmar (缅甸)' },
    { code: 'NA', name: 'Namibia (纳米比亚)' },
    { code: 'NR', name: 'Nauru (瑙鲁)' },
    { code: 'NP', name: 'Nepal (尼泊尔)' },
    { code: 'NL', name: 'Netherlands (荷兰)' },
    { code: 'AN', name: 'Netherlands Antilles (荷属安的列斯)' },
    { code: 'NC', name: 'New Caledonia (新喀里多尼亚)' },
    { code: 'NZ', name: 'New Zealand (新西兰)' },
    { code: 'NI', name: 'Nicaragua (尼加拉瓜)' },
    { code: 'NE', name: 'Niger (尼日尔)' },
    { code: 'NG', name: 'Nigeria (尼日利亚)' },
    { code: 'NU', name: 'Niue (纽埃)' },
    { code: 'NF', name: 'Norfolk Island (诺福克岛)' },
    { code: 'MP', name: 'Northern Mariana Islands (北马里亚纳群岛)' },
    { code: 'NO', name: 'Norway (挪威)' },
    { code: 'OM', name: 'Oman (阿曼)' },
    { code: 'PK', name: 'Pakistan (巴基斯坦)' },
    { code: 'PW', name: 'Palau (帕劳)' },
    { code: 'PS', name: 'Palestinian Territory (巴勒斯坦)' },
    { code: 'PA', name: 'Panama (巴拿马)' },
    { code: 'PG', name: 'Papua New Guinea (巴布亚新几内亚)' },
    { code: 'PY', name: 'Paraguay (巴拉圭)' },
    { code: 'PE', name: 'Peru (秘鲁)' },
    { code: 'PH', name: 'Philippines (菲律宾)' },
    { code: 'PN', name: 'Pitcairn (皮特凯恩)' },
    { code: 'PL', name: 'Poland (波兰)' },
    { code: 'PT', name: 'Portugal (葡萄牙)' },
    { code: 'PR', name: 'Puerto Rico (波多黎各)' },
    { code: 'QA', name: 'Qatar (卡塔尔)' },
    { code: 'RE', name: 'Reunion (留尼汪)' },
    { code: 'RO', name: 'Romania (罗马尼亚)' },
    { code: 'RU', name: 'Russian Federation (俄罗斯)' },
    { code: 'RW', name: 'Rwanda (卢旺达)' },
    { code: 'SH', name: 'Saint Helena (圣赫勒拿)' },
    { code: 'KN', name: 'Saint Kitts and Nevis (圣基茨和尼维斯)' },
    { code: 'LC', name: 'Saint Lucia (圣卢西亚)' },
    { code: 'PM', name: 'Saint Pierre and Miquelon (圣皮埃尔和密克隆)' },
    { code: 'VC', name: 'Saint Vincent and the Grenadines (圣文森特和格林纳丁斯)' },
    { code: 'WS', name: 'Samoa (萨摩亚)' },
    { code: 'SM', name: 'San Marino (圣马力诺)' },
    { code: 'ST', name: 'Sao Tome and Principe (圣多美和普林西比)' },
    { code: 'SA', name: 'Saudi Arabia (沙特阿拉伯)' },
    { code: 'SN', name: 'Senegal (塞内加尔)' },
    { code: 'CS', name: 'Serbia and Montenegro (塞尔维亚和黑山)' },
    { code: 'SC', name: 'Seychelles (塞舌尔)' },
    { code: 'SL', name: 'Sierra Leone (塞拉利昂)' },
    { code: 'SG', name: 'Singapore (新加坡)' },
    { code: 'SK', name: 'Slovakia (斯洛伐克)' },
    { code: 'SI', name: 'Slovenia (斯洛文尼亚)' },
    { code: 'SB', name: 'Solomon Islands (所罗门群岛)' },
    { code: 'SO', name: 'Somalia (索马里)' },
    { code: 'ZA', name: 'South Africa (南非)' },
    { code: 'GS', name: 'South Georgia and the South Sandwich Islands (南乔治亚岛和南桑威奇群岛)' },
    { code: 'ES', name: 'Spain (西班牙)' },
    { code: 'LK', name: 'Sri Lanka (斯里兰卡)' },
    { code: 'SD', name: 'Sudan (苏丹)' },
    { code: 'SR', name: 'Suriname (苏里南)' },
    { code: 'SJ', name: 'Svalbard and Jan Mayen (斯瓦尔巴群岛和扬马延岛)' },
    { code: 'SZ', name: 'Swaziland (斯威士兰)' },
    { code: 'SE', name: 'Sweden (瑞典)' },
    { code: 'CH', name: 'Switzerland (瑞士)' },
    { code: 'SY', name: 'Syrian Arab Republic (叙利亚)' },
    { code: 'TW', name: 'Taiwan (台湾)' },
    { code: 'TJ', name: 'Tajikistan (塔吉克斯坦)' },
    { code: 'TZ', name: 'Tanzania (坦桑尼亚)' },
    { code: 'TH', name: 'Thailand (泰国)' },
    { code: 'TL', name: 'Timor-Leste (东帝汶)' },
    { code: 'TG', name: 'Togo (多哥)' },
    { code: 'TK', name: 'Tokelau (托克劳)' },
    { code: 'TO', name: 'Tonga (汤加)' },
    { code: 'TT', name: 'Trinidad and Tobago (特立尼达和多巴哥)' },
    { code: 'TN', name: 'Tunisia (突尼斯)' },
    { code: 'TR', name: 'Turkey (土耳其)' },
    { code: 'TM', name: 'Turkmenistan (土库曼斯坦)' },
    { code: 'TC', name: 'Turks and Caicos Islands (特克斯和凯科斯群岛)' },
    { code: 'TV', name: 'Tuvalu (图瓦卢)' },
    { code: 'UG', name: 'Uganda (乌干达)' },
    { code: 'UA', name: 'Ukraine (乌克兰)' },
    { code: 'AE', name: 'United Arab Emirates (阿联酋)' },
    { code: 'GB', name: 'United Kingdom (英国)' },
    { code: 'US', name: 'United States (美国)' },
    { code: 'UM', name: 'United States Minor Outlying Islands (美属本土外小岛屿)' },
    { code: 'UY', name: 'Uruguay (乌拉圭)' },
    { code: 'UZ', name: 'Uzbekistan (乌兹别克斯坦)' },
    { code: 'VU', name: 'Vanuatu (瓦努阿图)' },
    { code: 'VE', name: 'Venezuela (委内瑞拉)' },
    { code: 'VN', name: 'Vietnam (越南)' },
    { code: 'VG', name: 'Virgin Islands, British (英属维尔京群岛)' },
    { code: 'VI', name: 'Virgin Islands, U.S. (美属维尔京群岛)' },
    { code: 'WF', name: 'Wallis and Futuna (瓦利斯和富图纳)' },
    { code: 'EH', name: 'Western Sahara (西撒哈拉)' },
    { code: 'YE', name: 'Yemen (也门)' },
    { code: 'ZM', name: 'Zambia (赞比亚)' },
    { code: 'ZW', name: 'Zimbabwe (津巴布韦)' },
];
